#line 2 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.cpp"

#line 4 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ISO__create_buffer
#define yy_delete_buffer ISO__delete_buffer
#define yy_flex_debug ISO__flex_debug
#define yy_init_buffer ISO__init_buffer
#define yy_flush_buffer ISO__flush_buffer
#define yy_load_buffer_state ISO__load_buffer_state
#define yy_switch_to_buffer ISO__switch_to_buffer
#define yyin ISO_in
#define yyleng ISO_leng
#define yylex ISO_lex
#define yylineno ISO_lineno
#define yyout ISO_out
#define yyrestart ISO_restart
#define yytext ISO_text
#define yywrap ISO_wrap
#define yyalloc ISO_alloc
#define yyrealloc ISO_realloc
#define yyfree ISO_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ISO_restart(ISO_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ISO_leng;

extern FILE *ISO_in, *ISO_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ISO_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ISO_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ISO_restart()), so that the user can continue scanning by
	 * just pointing ISO_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ISO_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ISO_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ISO_wrap()'s to do buffer switches
 * instead of setting up a fresh ISO_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ISO_restart (FILE *input_file  );
void ISO__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ISO__create_buffer (FILE *file,int size  );
void ISO__delete_buffer (YY_BUFFER_STATE b  );
void ISO__flush_buffer (YY_BUFFER_STATE b  );
void ISO_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void ISO_pop_buffer_state (void );

static void ISO_ensure_buffer_stack (void );
static void ISO__load_buffer_state (void );
static void ISO__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ISO__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ISO__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ISO__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ISO__scan_bytes (yyconst char *bytes,int len  );

void *ISO_alloc (yy_size_t  );
void *ISO_realloc (void *,yy_size_t  );
void ISO_free (void *  );

#define yy_new_buffer ISO__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ISO_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ISO__create_buffer(ISO_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ISO_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ISO__create_buffer(ISO_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ISO_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ISO_in = (FILE *) 0, *ISO_out = (FILE *) 0;

typedef int yy_state_type;

extern int ISO_lineno;

int ISO_lineno = 1;

extern char *ISO_text;
#define yytext_ptr ISO_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ISO_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ISO_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
        0,    0,   50,   48,    1,    1,   44,   36,   37,   46,
       32,   45,   42,   34,   33,   35,   47,   30,   40,   43,
       41,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   38,   39,   31,   32,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,    9,   24,   30,   30,   31,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   14,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   25,   30,   30,    8,   13,
       30,   30,   30,    5,   30,   30,   30,   30,   16,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   10,   17,
       30,   30,   30,   30,   30,   30,   30,   30,    3,   30,
       30,   30,   30,   30,   30,   30,   30,   27,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   23,
       30,   30,    4,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,    6,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       18,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   11,   30,   30,   30,   30,   30,   29,
       30,   30,   28,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,    2,   30,
       30,   21,   12,   30,   30,   30,   30,   30,   30,   22,
        7,   30,   30,   15,   30,   30,   30,   30,   30,   30,

       30,   30,   26,   30,   19,   20,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,   13,
       14,   15,    1,   16,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,   19,   20,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   17,   17,   31,   32,   33,
       34,   35,   17,   36,   37,   38,   39,   40,   41,   17,
       42,   17,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[45] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1
    } ;

static yyconst flex_int16_t yy_base[309] =
    {   0,
        0,    0,  318,  319,  319,  319,  319,  319,  319,  319,
       37,  319,  319,  319,  319,  319,  319,    0,  319,  319,
      319,  283,   20,   23,   18,  280,  285,   17,  280,  291,
      273,  277,  275,   30,  319,  319,  299,   50,    0,  269,
      276,  280,  278,  268,   27,  265,  280,  267,  272,   26,
      265,  257,  265,  258,    0,    0,  264,  263,  283,  259,
      260,  268,   40,  263,  266,  254,  257,  262,  252,  254,
      243,  243,  249,    0,  253,  243,  247,  238,  250,  237,
      235,  233,  238,  246,  239,    0,  242,  236,    0,    0,
      228,  243,  242,    0,  224,  237,  239,  238,    0,  233,

      227,  231,  218,  222,  218,  227,  231,  218,  212,  211,
      227,  219,  210,  224,  206,  222,  212,  220,    0,    0,
      200,  215,  208,  216,  205,  209,  192,   36,    0,   42,
      199,  208,  197,  204,  195,  188,  193,    0,  205,  188,
      198,  189,  188,  184,  194,  186,  184,  186,  179,  182,
      180,  189,  177,  177,  170,  177,  167,  173,  166,    0,
      172,  166,    0,  182,  171,  179,  166,  168,  172,  167,
      170,  164,  168,  168,  170,   31,  153,  152,  153,  166,
      156,  153,  149,  162,  152,  152,  153,  146,  140,  156,
      147,  138,  137,  153,  151,  151,  133,  149,  131,  142,

      134,  128,  137,  130,  126,  132,  124,  129,   49,  129,
      121,  127,  135,  130,  119,  127,  119,    0,  117,  121,
      128,  114,  113,  112,  116,  110,  107,  112,  102,  119,
        0,  106,  108,  113,  104,  110,  101,  103,   99,  109,
       92,   91,   92,  106,   99,   91,  102,   97,  101,   94,
       83,   86,   88,    0,   95,   80,   77,   81,   83,    0,
       88,   73,    0,   82,   75,   75,   68,   80,   80,   71,
       77,   76,   75,   67,   71,   67,   61,   66,    0,   64,
       58,    0,    0,   67,   66,   70,   52,   58,   67,    0,
        0,   51,   56,    0,   61,   45,   49,   56,   49,   46,

       47,   51,    0,   45,    0,    0,  319,   73
    } ;

static yyconst flex_int16_t yy_def[309] =
    {   0,
      307,    1,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  308,  307,  307,
      307,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  307,  307,  307,  307,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  307,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,    0,  307
    } ;

static yyconst flex_int16_t yy_nxt[364] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,    4,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       18,   18,   22,   23,   24,   25,   26,   18,   27,   28,
       29,   18,   30,   31,   18,   18,   18,   32,   33,   34,
       18,   18,   35,   36,   37,   41,   38,   46,   43,   50,
       47,   57,   44,   51,  188,   42,   45,   37,   65,   38,
       71,   82,   72,   58,  189,  140,  141,   66,  142,   83,
      143,  144,  145,  222,   39,  306,  305,  304,  303,  302,
      223,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,

      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  187,  186,  185,  184,  183,  182,  181,  180,  179,

      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   81,
       80,   79,   59,   78,   77,   76,   75,   74,   73,   70,

       69,   68,   67,   64,   63,   62,   61,   60,   59,   56,
       55,   54,   53,   52,   49,   48,   40,  307,    3,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[364] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   11,   23,   11,   25,   24,   28,
       25,   34,   24,   28,  176,   23,   24,   38,   45,   38,
       50,   63,   50,   34,  176,  128,  128,   45,  128,   63,
      128,  130,  130,  209,  308,  304,  302,  301,  300,  299,
      209,  298,  297,  296,  295,  293,  292,  289,  288,  287,
      286,  285,  284,  281,  280,  278,  277,  276,  275,  274,

      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      262,  261,  259,  258,  257,  256,  255,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  217,  216,  215,  214,  213,  212,  211,  210,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  175,  174,  173,  172,  171,  170,  169,  168,  167,

      166,  165,  164,  162,  161,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  137,  136,  135,  134,
      133,  132,  131,  127,  126,  125,  124,  123,  122,  121,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   98,
       97,   96,   95,   93,   92,   91,   88,   87,   85,   84,
       83,   82,   81,   80,   79,   78,   77,   76,   75,   73,
       72,   71,   70,   69,   68,   67,   66,   65,   64,   62,
       61,   60,   59,   58,   57,   54,   53,   52,   51,   49,

       48,   47,   46,   44,   43,   42,   41,   40,   37,   33,
       32,   31,   30,   29,   27,   26,   22,    3,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ISO__flex_debug;
int ISO__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ISO_text;
#line 1 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
#line 2 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
#include <string>
#include "ISO_Parser.hpp"
#define SAVE_TOKEN ISO_lval.iso_string = new std::string(ISO_text, ISO_leng)
#define TOKEN(t) (ISO_lval.token = t)
#line 667 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ISO_lex_destroy (void );

int ISO_get_debug (void );

void ISO_set_debug (int debug_flag  );

YY_EXTRA_TYPE ISO_get_extra (void );

void ISO_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *ISO_get_in (void );

void ISO_set_in  (FILE * in_str  );

FILE *ISO_get_out (void );

void ISO_set_out  (FILE * out_str  );

int ISO_get_leng (void );

char *ISO_get_text (void );

int ISO_get_lineno (void );

void ISO_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ISO_wrap (void );
#else
extern int ISO_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ISO_text, ISO_leng, 1, ISO_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ISO_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ISO_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ISO_in))==0 && ferror(ISO_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ISO_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ISO_lex (void);

#define YY_DECL int ISO_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ISO_text and ISO_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 11 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"


#line 857 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ISO_in )
			ISO_in = stdin;

		if ( ! ISO_out )
			ISO_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ISO_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ISO__create_buffer(ISO_in,YY_BUF_SIZE );
		}

		ISO__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ISO_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 319 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 13 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCREATE_POWER_DOMAIN);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDEFAULT);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TINSTANCES);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TNAME);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TBOUNDARY_PORTS);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCREATE_ISOLATION_RULE);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TFROM);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TTO);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TEITHER);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TISOLATION_OUTPUT);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TISOLATION_CONDITION);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(THIGH);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TLOW);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDEFINE_ISOLATION_CELL);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCELLS);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TENABLE);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TVALID_LOCATION);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCREATE_LEVEL_SHIFTER_RULE);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDEFINE_LEVEL_SHIFTER_CELL);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TINPUT_VOLTAGE_RANGE);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TOUTPUT_VOLTAGE_RANGE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDIRECTION);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TUP);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDOWN);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCREATE_NOMINAL_CONDITION);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TVOLTAGE);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TDOMAIN_CONDITIONS);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCREATE_POWER_MODE);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
SAVE_TOKEN; return TIDENTIFIER;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
SAVE_TOKEN; return TDOUBLE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
SAVE_TOKEN; return TINTEGER;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TEQUAL);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCLT);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCGT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TLPAREN);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TRPAREN);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TLBRACE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TRBRACE);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TLSQUARE);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TRSQUARE);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TEND);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TSLASH);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TINV);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TCOLON);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TMINUS);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
return TOKEN(TAT);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
printf("Unknown token!\n"); yyterminate();
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 63 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"
ECHO;
	YY_BREAK
#line 1186 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ISO_in at a new source and called
			 * ISO_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ISO_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ISO_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ISO_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ISO_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ISO_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ISO_restart(ISO_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ISO_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ISO_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ISO_restart(ISO_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ISO_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ISO_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ISO_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ISO_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ISO__create_buffer(ISO_in,YY_BUF_SIZE );
	}

	ISO__init_buffer(YY_CURRENT_BUFFER,input_file );
	ISO__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ISO__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ISO_pop_buffer_state();
	 *		ISO_push_buffer_state(new_buffer);
     */
	ISO_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ISO__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ISO_wrap()) processing, but the only time this flag
	 * is looked at is after ISO_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ISO__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ISO_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ISO__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ISO_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ISO__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ISO_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ISO__create_buffer()" );

	b->yy_is_our_buffer = 1;

	ISO__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ISO__create_buffer()
 * 
 */
    void ISO__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ISO_free((void *) b->yy_ch_buf  );

	ISO_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ISO_restart() or at EOF.
 */
    static void ISO__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ISO__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ISO__init_buffer was _probably_
     * called from ISO_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ISO__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ISO__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ISO_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ISO_ensure_buffer_stack();

	/* This block is copied from ISO__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ISO__switch_to_buffer. */
	ISO__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ISO_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ISO__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ISO__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ISO_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ISO_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ISO_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ISO_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ISO_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ISO__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ISO_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ISO__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ISO__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ISO_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ISO__scan_bytes() instead.
 */
YY_BUFFER_STATE ISO__scan_string (yyconst char * yystr )
{
    
	return ISO__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ISO_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ISO__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ISO_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ISO__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ISO__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ISO__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ISO_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ISO_text[ISO_leng] = (yy_hold_char); \
		(yy_c_buf_p) = ISO_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ISO_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ISO_get_lineno  (void)
{
        
    return ISO_lineno;
}

/** Get the input stream.
 * 
 */
FILE *ISO_get_in  (void)
{
        return ISO_in;
}

/** Get the output stream.
 * 
 */
FILE *ISO_get_out  (void)
{
        return ISO_out;
}

/** Get the length of the current token.
 * 
 */
int ISO_get_leng  (void)
{
        return ISO_leng;
}

/** Get the current token.
 * 
 */

char *ISO_get_text  (void)
{
        return ISO_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ISO_set_lineno (int  line_number )
{
    
    ISO_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ISO__switch_to_buffer
 */
void ISO_set_in (FILE *  in_str )
{
        ISO_in = in_str ;
}

void ISO_set_out (FILE *  out_str )
{
        ISO_out = out_str ;
}

int ISO_get_debug  (void)
{
        return ISO__flex_debug;
}

void ISO_set_debug (int  bdebug )
{
        ISO__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ISO_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ISO_in = stdin;
    ISO_out = stdout;
#else
    ISO_in = (FILE *) 0;
    ISO_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ISO_lex_init()
     */
    return 0;
}

/* ISO_lex_destroy is for both reentrant and non-reentrant scanners. */
int ISO_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ISO__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ISO_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	ISO_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ISO_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ISO_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ISO_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ISO_free (void * ptr )
{
	free( (char *) ptr );	/* see ISO_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 63 "/home/sean/桌面/iso_cell_rc1/kernel/ISO_Parser/ISO_Tokens.l"



